version: '3.3'

services:

  cottontail:
    container_name: cottontail
    image: vitrivr/cottontaildb:latest
    ports:
      - 1865:1865
    volumes:
      - ./data/cottontail/:/cottontaildb-data
      - ./config/cottontail/config.json:/cottontaildb-config/config.json

  cineast:
    container_name: cineast
    build:
      context: ./cineast-docker/
      dockerfile: Dockerfile
    depends_on:
      - cottontail
    ports:
      - 4567:4567  # http api
      - 4568:4568  # https api
      - 4569:4569  # Prometheus
    volumes:
      # - ./cineast-docker/config-v3.7.2.json:/config.json
      - ./cineast-docker/config-v3.12.4.json:/config.json
      - ./cineast-docker/extraction_config.json:/extraction_config.json  # see sessionExtractionConfigLocation in config.json
      - ./media:/data  # /data is refered to in extraction_config.json

  vitrivr-ng:
    container_name: vitrivr-ng
    build:
      context: ./vitrivr-ng-docker/
      dockerfile: Dockerfile
    ports:
      - 88:80  # http

